version: "3.9"
services:

  #PHP
  www:
    build: php
    container_name: php_ParcAuto_docker
    ports:
      - "8001:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - parcAuto

  #NODE
  nodejs:
    image: node:14-alpine
    container_name: nodejs_ParcAuto_docker
    volumes:
      - ./:/var/www/ParcAuto/
    networks:
      - parcAuto

  # mysql
  mysql:
    image: mysql:5.7
    container_name: mysql_ParcAuto_docker
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - parcAuto

  #Adminer
  adminer:
    image: adminer
    container_name: adminer_intranet_docker
    restart: always
    ports:
      - 8080:8080
    networks:
      - parcAuto

volumes :
  db-data:
networks:
  parcAuto:


